version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/PigeonPulse
    overwrite: yes

permissions:
  - object: /home/ec2-user/PigeonPulse
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/PigeonPulse/static
    owner: nginx
    group: nginx
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/PigeonPulse/scripts
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/PigeonPulse/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
