version: 0.1
os: linux

files:
  - source: /
    destination: /home/ec2-user/PigeonPulse
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
