version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/PigeonPulse/

permissions:
  - object: /home/ec2-user/PigeonPulse/
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/PigeonPulse/scripts/
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/PigeonPulse/scripts/deploy.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /home/ec2-user/PigeonPulse/scripts/before_install.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
