version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/PigeonPulse/
permissions:
  - object: /home/ec2-user/PigeonPulse/
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/frontend_install.sh
      timeout: 300
      runas: ec2-user
