version: 0.0
os: linux

files:
  - source: /publish
    destination: /home/ec2-user/PigeonPulse/publish
  - source: /scripts
    destination: /home/ec2-user/PigeonPulse/scripts
  - source: /database/application/migrations          
    destination: /home/ec2-user/PigeonPulse/database/application/migrations

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
