version: 0.0
os: linux
files:
  - source: client
    destination: /home/ec2-user/PigeonPulse/client
  - source: server-publish
    destination: /home/ec2-user/PigeonPulse/server-publish
  - source: server-publish/static
    destination: /home/ec2-user/PigeonPulse/static
  - source: scripts/deploy.sh
    destination: /home/ec2-user/PigeonPulse/scripts
  - source: scripts/before_install.sh
    destination: /home/ec2-user/PigeonPulse/scripts
permissions:
  - object: /home/ec2-user/PigeonPulse
    owner: ec2-user
    group: ec2-user
    type: directory
    pattern: "*"
  - object: /home/ec2-user/PigeonPulse/static
    owner: nginx
    group: nginx
    type: directory
    pattern: "*"
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 900
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user