version: 0.0
os: linux
files:
  - source: publish
    destination: /home/ec2-user/PigeonPulse
    exclude:
      - static/**
  - source: publish/static
    destination: /home/ec2-user/PigeonPulse/static
  - source: appspec.yml
    destination: /home/ec2-user/PigeonPulse
  - source: scripts
    destination: /home/ec2-user/PigeonPulse/scripts

permissions:
  - object: /home/ec2-user/PigeonPulse
    owner: ec2-user
    group: ec2-user
    type: directory
    mode: 755
  - object: /home/ec2-user/PigeonPulse/static
    owner: nginx
    group: nginx
    type: directory
    mode: 755
  - object: /home/ec2-user/PigeonPulse/scripts
    owner: ec2-user
    group: ec2-user
    type: directory
    mode: 755
  - object: /home/ec2-user/PigeonPulse/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    type: file
    mode: 755  # Ensure scripts are executable

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
