version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 8.0.201
      - export PATH="$HOME/.dotnet:$PATH"
      - dotnet --version
      - npm install --prefix client
      - dotnet restore server/src/PigeonPulse.Api

  build:
    commands:
      - echo "Building the React frontend..."
      - npm run build --prefix client
      - echo "Building the ASP.NET backend..."
      - dotnet build server/src/PigeonPulse.Api --configuration Release

  post_build:
    commands:
      - echo "Publishing ASP.NET backend..."
      - dotnet publish server/src/PigeonPulse.Api --configuration Release --output ./publish

artifacts:
  files:
    - '**/*'
  base-directory: publish
  discard-paths: no
