version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd client # Ensure we are in the correct directory
      - npm install
  
  build:
    commands:
      - echo "Building frontend..."
      - npm run build
      - echo "Building backend..."
      - cd ../server # Adjust if needed
      - dotnet restore
      - dotnet publish -c Release -o ../publish
  
  post_build:
    commands:
      - echo "Build complete, preparing artifacts..."

artifacts:
  files:
    - appspec.yml
    - before_install.sh
    - deploy.sh
    - publish/**/*
    - client/dist/**/* # Ensure the frontend is included
