version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # ✅ Ensures CodeBuild uses Node.js 18
    commands:
      - echo "Installing dependencies..."
      - cd client
      - npm install
  
  build:
    commands:
      - echo "Building frontend..."
      - npm run build -- --openssl-legacy-provider
      - echo "Building backend..."
      - cd ../server # Adjust if needed
      - dotnet restore
      - dotnet publish -c Release -o ../publish
  
  post_build:
    commands:
      - echo "Build complete, preparing artifacts..."

artifacts:
  files:
    - appspec.yml
    - before_install.sh
    - deploy.sh
    - publish/**/*
    - client/dist/**/* # Ensure the frontend is included
