version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix client
      - dotnet restore server/src/PigeonPulse.sln

  build:
    commands:
      - echo "Building the React frontend..."
      - npm run build --prefix client || { echo "Frontend build failed"; exit 1; }
      - echo "Verifying frontend build output..."
      - ls -la client/dist || { echo "dist directory missing after build"; exit 1; }
      - echo "Building the ASP.NET backend..."
      - dotnet build server/src/PigeonPulse.sln --configuration Release || { echo "Backend build failed"; exit 1; }

  post_build:
    commands:
      - echo "Publishing ASP.NET backend..."
      - rm -rf server-publish
      - dotnet publish server/src/PigeonPulse.Api --configuration Release --output ./server-publish --no-restore
      - echo "Verifying publish output..."
      - ls -la server-publish || { echo "server-publish directory missing after publish"; exit 1; }
      - echo "Copying dist to server-publish/static for deployment..."
      - mkdir -p server-publish/static
      - cp -r client/dist/* server-publish/static || { echo "Failed to copy dist to static"; exit 1; }
      - echo "Verifying static contents..."
      - ls -la server-publish/static || { echo "static directory missing after copy"; exit 1; }

artifacts:
  files:
    - appspec.yml
    - scripts/before_install.sh
    - scripts/deploy.sh
    - server-publish/**
  discard-paths: no
cache:
  paths: []