version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      dotnet: 8.0.100  # Specify a precise version like 8.0.100
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix client
      - dotnet restore server/src/PigeonPulse.sln

  build:
    commands:
      - echo "Building the React frontend..."
      - npm run build --prefix client
      - echo "Publishing the ASP.NET backend..."
      - dotnet publish server/src/PigeonPulse.Api --configuration Release --output ./publish
      - echo "Copying static files to publish directory..."
      - mkdir -p publish/static
      - cp -r client/dist/* publish/static/
      - echo "Build completed."

artifacts:
  files:
    - appspec.yml
    - publish/**
  discard-paths: no
cache:
  paths: []