version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix client
      - dotnet restore server/src/PigeonPulse.Api

  build:
    commands:
      - echo "Building frontend..."
      - npm run build --prefix client
      - echo "Building backend..."
      - dotnet publish server/src/PigeonPulse.Api -c Release -o published

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Preparing artifacts..."

artifacts:
  files:
    - client/dist/**/*
    - published/**/*
    - scripts/**
  discard-paths: no
