version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir $HOME/.dotnet --version 8.0.204
      - export PATH="$HOME/.dotnet:$PATH"
      - dotnet --version
      - npm install --prefix client
      - dotnet restore server/src/PigeonPulse.sln  # Restore the whole solution for consistency

  build:
    commands:
      - echo "Building the React frontend..."
      - npm run build --prefix client || { echo "Frontend build failed"; exit 1; }
      - echo "Building the ASP.NET backend..."
      - dotnet build server/src/PigeonPulse.sln --configuration Release || { echo "Backend build failed"; exit 1; }

  post_build:
    commands:
      - echo "Publishing ASP.NET backend..."
      - rm -rf server-publish
      - dotnet publish server/src/PigeonPulse.Api --configuration Release --output ./server-publish --no-restore
      - echo "Verifying publish output..."
      - ls -la server-publish  # Debug step to ensure files are generated

artifacts:
  files:
    - appspec.yml
    - scripts/deploy.sh
    - scripts/before_install.sh
    - client/**
    - server-publish/**
  discard-paths: no
cache:
  paths: []