version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --install-dir /usr/share/dotnet --version 8.0.201
      - export PATH="/usr/share/dotnet:$PATH"
      - echo 'export PATH="/usr/share/dotnet:$PATH"' >> ~/.bashrc
      - source ~/.bashrc
      - dotnet --version
      - npm install --prefix client
      - dotnet restore server/src/PigeonPulse.Api

  build:
    commands:
      - echo "Building the React frontend..."
      - npm run build --prefix client || echo "Frontend build failed"
      - echo "Building the ASP.NET backend..."
      - dotnet build server/src/PigeonPulse.Api --configuration Release || echo "Backend build failed"

  post_build:
    commands:
      - echo "Publishing ASP.NET backend..."
      - dotnet publish server/src/PigeonPulse.Api --configuration Release --output ./server-publish

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - client/**/*
    - server-publish/**/*
  discard-paths: no
