services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pigeonpulse
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: pigeonpulse-dev
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/pigeonpulse-dev -schemas=public -user=pigeonpulse -password=password1 -outOfOrder=true -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
volumes:
  db: